
@startuml

start
:Cart Screen;
:View Cart Items;
if (Confirm Order?) then (yes)
  :Order Confirmation Screen;
  :Confirm;
else (no)
  :Continue Shopping Screen;
  :Add More Products;
  -->Cart Screen;
endif
stop
@enduml











'|Dealer Home|
':Display DealerHome;
':Display Companies;
'if (Select Company) then (yes)
'  :Display Selected Company Products;
'  :Select product;
'else if(Forgot Password) then (yes)
'  :Redirect to Dealer Forgot Password Screen;
'else if(Click Logout)
'  :Redirected to DealerLogin;
'else if(Update Account)
'  :Display Account Screen;
'  stop
'endif





|Farmers Home|
:Display FarmersHome;
:Display Weather;
if (Click Calculate Fertilizer) then (yes)
  :Display Fertilizer Calculator;

else if(Click Logout)
  :Redirected to FarmersLogin;
else if(Click Diseases)
  :Display Diseases Screen;
  stop
endif

@enduml
